# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history_dia.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_History_stop(object):
    def setupUi(self, History_stop):
        History_stop.setObjectName("History_stop")
        History_stop.resize(530, 675)
        self.history_username_label = QtWidgets.QLabel(History_stop)
        self.history_username_label.setGeometry(QtCore.QRect(10, 20, 200, 45))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.history_username_label.setFont(font)
        self.history_username_label.setObjectName("history_username_label")
        self.history_phonenumber_label = QtWidgets.QLabel(History_stop)
        self.history_phonenumber_label.setGeometry(QtCore.QRect(10, 90, 200, 45))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.history_phonenumber_label.setFont(font)
        self.history_phonenumber_label.setObjectName("history_phonenumber_label")
        self.history_car_factory_label = QtWidgets.QLabel(History_stop)
        self.history_car_factory_label.setGeometry(QtCore.QRect(10, 160, 200, 45))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.history_car_factory_label.setFont(font)
        self.history_car_factory_label.setObjectName("history_car_factory_label")
        self.history_car_model_label = QtWidgets.QLabel(History_stop)
        self.history_car_model_label.setGeometry(QtCore.QRect(10, 230, 200, 45))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.history_car_model_label.setFont(font)
        self.history_car_model_label.setObjectName("history_car_model_label")
        self.history_car_color_label = QtWidgets.QLabel(History_stop)
        self.history_car_color_label.setGeometry(QtCore.QRect(10, 300, 200, 45))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.history_car_color_label.setFont(font)
        self.history_car_color_label.setObjectName("history_car_color_label")
        self.history_car_plate_label = QtWidgets.QLabel(History_stop)
        self.history_car_plate_label.setGeometry(QtCore.QRect(10, 370, 200, 45))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.history_car_plate_label.setFont(font)
        self.history_car_plate_label.setObjectName("history_car_plate_label")
        self.history_into_time_label = QtWidgets.QLabel(History_stop)
        self.history_into_time_label.setGeometry(QtCore.QRect(10, 440, 200, 45))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.history_into_time_label.setFont(font)
        self.history_into_time_label.setObjectName("history_into_time_label")
        self.history_leave_tiame_label = QtWidgets.QLabel(History_stop)
        self.history_leave_tiame_label.setGeometry(QtCore.QRect(10, 510, 200, 45))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.history_leave_tiame_label.setFont(font)
        self.history_leave_tiame_label.setObjectName("history_leave_tiame_label")
        self.history_username_info = QtWidgets.QLabel(History_stop)
        self.history_username_info.setGeometry(QtCore.QRect(220, 20, 200, 45))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.history_username_info.setFont(font)
        self.history_username_info.setObjectName("history_username_info")
        self.history_phonenumber_info = QtWidgets.QLabel(History_stop)
        self.history_phonenumber_info.setGeometry(QtCore.QRect(220, 90, 200, 45))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.history_phonenumber_info.setFont(font)
        self.history_phonenumber_info.setObjectName("history_phonenumber_info")
        self.history_car_model_info = QtWidgets.QLabel(History_stop)
        self.history_car_model_info.setGeometry(QtCore.QRect(220, 230, 200, 45))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.history_car_model_info.setFont(font)
        self.history_car_model_info.setObjectName("history_car_model_info")
        self.history_car_factory_info = QtWidgets.QLabel(History_stop)
        self.history_car_factory_info.setGeometry(QtCore.QRect(220, 160, 200, 45))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.history_car_factory_info.setFont(font)
        self.history_car_factory_info.setObjectName("history_car_factory_info")
        self.history_leave_tiame_info = QtWidgets.QLabel(History_stop)
        self.history_leave_tiame_info.setGeometry(QtCore.QRect(220, 510, 300, 45))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(13)
        self.history_leave_tiame_info.setFont(font)
        self.history_leave_tiame_info.setObjectName("history_leave_tiame_info")
        self.history_into_time_info = QtWidgets.QLabel(History_stop)
        self.history_into_time_info.setGeometry(QtCore.QRect(220, 440, 300, 45))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(13)
        self.history_into_time_info.setFont(font)
        self.history_into_time_info.setObjectName("history_into_time_info")
        self.history_car_plate_info = QtWidgets.QLabel(History_stop)
        self.history_car_plate_info.setGeometry(QtCore.QRect(220, 370, 200, 45))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.history_car_plate_info.setFont(font)
        self.history_car_plate_info.setObjectName("history_car_plate_info")
        self.history_next_note_btn = QtWidgets.QPushButton(History_stop)
        self.history_next_note_btn.setGeometry(QtCore.QRect(430, 570, 50, 40))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.history_next_note_btn.setFont(font)
        self.history_next_note_btn.setStyleSheet("QPushButton{\n"
"    background-color:rgba(255,255,255,0);\n"
"}\n"
"QPushButton:hover{\n"
"    color:pink;\n"
"    font-size:20px;\n"
"}")
        self.history_next_note_btn.setObjectName("history_next_note_btn")
        self.history_car_color_info = QtWidgets.QLabel(History_stop)
        self.history_car_color_info.setGeometry(QtCore.QRect(220, 300, 200, 45))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.history_car_color_info.setFont(font)
        self.history_car_color_info.setObjectName("history_car_color_info")
        self.history_tooltip_label = QtWidgets.QLabel(History_stop)
        self.history_tooltip_label.setGeometry(QtCore.QRect(10, 620, 220, 40))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.history_tooltip_label.setFont(font)
        self.history_tooltip_label.setStyleSheet("QLabel{\n"
"    color:red;\n"
"\n"
"}")
        self.history_tooltip_label.setObjectName("history_tooltip_label")
        self.history_previous_note_btn = QtWidgets.QPushButton(History_stop)
        self.history_previous_note_btn.setGeometry(QtCore.QRect(350, 570, 50, 40))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.history_previous_note_btn.setFont(font)
        self.history_previous_note_btn.setStyleSheet("QPushButton{\n"
"    background-color:rgba(255,255,255,0);\n"
"}\n"
"QPushButton:hover{\n"
"    color:pink;\n"
"    font-size:20px;\n"
"}\n"
"")
        self.history_previous_note_btn.setObjectName("history_previous_note_btn")
        self.history_note_tooltip_label = QtWidgets.QLabel(History_stop)
        self.history_note_tooltip_label.setGeometry(QtCore.QRect(350, 620, 171, 40))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.history_note_tooltip_label.setFont(font)
        self.history_note_tooltip_label.setObjectName("history_note_tooltip_label")

        self.retranslateUi(History_stop)
        QtCore.QMetaObject.connectSlotsByName(History_stop)

    def retranslateUi(self, History_stop):
        _translate = QtCore.QCoreApplication.translate
        History_stop.setWindowTitle(_translate("History_stop", "Dialog"))
        self.history_username_label.setText(_translate("History_stop", "用户名"))
        self.history_phonenumber_label.setText(_translate("History_stop", "电话"))
        self.history_car_factory_label.setText(_translate("History_stop", "汽车厂商"))
        self.history_car_model_label.setText(_translate("History_stop", "汽车型号"))
        self.history_car_color_label.setText(_translate("History_stop", "汽车颜色"))
        self.history_car_plate_label.setText(_translate("History_stop", "车牌号"))
        self.history_into_time_label.setText(_translate("History_stop", "进入时间"))
        self.history_leave_tiame_label.setText(_translate("History_stop", "离开时间"))
        self.history_username_info.setText(_translate("History_stop", "张三"))
        self.history_phonenumber_info.setText(_translate("History_stop", "13312345678"))
        self.history_car_model_info.setText(_translate("History_stop", "宝马X1"))
        self.history_car_factory_info.setText(_translate("History_stop", "宝马"))
        self.history_leave_tiame_info.setText(_translate("History_stop", "2018-11-01 22：59：55"))
        self.history_into_time_info.setText(_translate("History_stop", "2018-11-01 22：59：55"))
        self.history_car_plate_info.setText(_translate("History_stop", "粤B.88888"))
        self.history_next_note_btn.setText(_translate("History_stop", "🔻"))
        self.history_next_note_btn.setShortcut(_translate("History_stop", "Down"))
        self.history_car_color_info.setText(_translate("History_stop", "银色"))
        self.history_tooltip_label.setText(_translate("History_stop", "没有更多记录了"))
        self.history_previous_note_btn.setText(_translate("History_stop", "🔺"))
        self.history_previous_note_btn.setShortcut(_translate("History_stop", "Up"))
        self.history_note_tooltip_label.setText(_translate("History_stop", "第1条，共3条"))

